# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: password
                        roles: 'ROLE_ADMIN'

    encoders:
            Symfony\Component\Security\Core\User\User: plaintext

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin_public:
            pattern: ^/admin/login
            security: false
            methods: [GET]

        admin_secured:
            pattern: ^/admin
            security: true
            provider: in_memory
            form_login:
                login_path: admin_login
                check_path: admin_login
                default_target_path: admin_default
            logout:
                path: /admin/logout
                target: admin_login

        main:
            anonymous: ~

    access_control:
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
